/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE `custom_transmogrification` (
  `GUID` INT(10) UNSIGNED NOT NULL COMMENT 'Item guidLow',
  `FakeEntry` INT(10) UNSIGNED NOT NULL COMMENT 'Item entry',
  `Owner` INT(10) UNSIGNED NOT NULL COMMENT 'Player guidLow',
  PRIMARY KEY (`GUID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;

CREATE TABLE `custom_transmogrification_sets` (
  `Owner` INT(10) UNSIGNED NOT NULL COMMENT 'Player guidlow',
  `PresetID` TINYINT(3) UNSIGNED NOT NULL COMMENT 'Preset identifier',
  `SetName` TEXT COMMENT 'SetName',
  `SetData` TEXT COMMENT 'Slot1 Entry1 Slot2 Entry2',
  PRIMARY KEY (`Owner`,`PresetID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;