REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (91919, 0, 0, 0, 0, 0, 25036, 0, 0, 0, 'Custom Teleporter', 'Teleporteris', '', 60010, 1, 1, 0, 1, 1, 1.14286, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, '');

REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag) VALUES 
(60010, 1, 4, 'Teleport me to Enchanting!', 1, 1), -- X: -361.803; Y: 1582.094; Z: 18.049; O: 0.047
(60010, 2, 4, 'Teleport me to Tailoring or Leatherworking!', 1, 1), -- X: -402.001; Y: 1598.580; Z: 18.105; O: 2.258
(60010, 3, 4, 'Teleport me to Engineering!', 1, 1), -- X: -432.177; Y: 1557.397; Z: 19.716; O: 2.146;
(60010, 4, 4, 'Teleport me to Jewelcrafting', 1, 1), --  X: -439.899; Y: 1538.911; Z: 19.636; O: 3.140
(60010, 5, 4, 'Teleport me to Alchemy!', 1, 1), -- X: -432.523; Y: 1521.334; Z: 19.547; O: 4.138
(60010, 6, 4, 'Teleport me to Blacksmithing', 1, 1), -- X: -345.285; Y: 1502.167, Z: 18.809, O: 1.962
(60010, 7, 4, 'Teleport me to Inscription', 1, 1); -- Area: 204, X: -333.014; Y: 1525.338; Z: 17.986; O: 1.627 

REPLACE INTO gossip_menu(entry, text_id) VALUES (60010, 60010);

-- Generated by Event Horizon - SAI Editor (http://devsource-eventhorizon.tk/)

-- Custom Teleporter
SET @ENTRY := 91919;
SET @SOURCETYPE := 0;

DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=@SOURCETYPE;
UPDATE creature_template SET AIName="SmartAI" WHERE entry=@ENTRY LIMIT 1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES 
(@ENTRY,@SOURCETYPE,0,0,62,0,100,0,60010,1,0,0,62,0,0,0,0,0,0,7,0,0,0,-361.803,1582.09,18.049,0.047,"Teleport to Enchanting"),
(@ENTRY,@SOURCETYPE,1,0,62,0,100,0,60010,2,0,0,62,0,0,0,0,0,0,7,0,0,0,-402.001,1598.58,18.105,2.258,"Teleport to Tailoring or Leatherworking"),
(@ENTRY,@SOURCETYPE,2,0,62,0,100,0,60010,3,0,0,62,0,0,0,0,0,0,7,0,0,0,-432.177,1557.4,19.716,2.146,"Teleport to Engineering"),
(@ENTRY,@SOURCETYPE,3,0,62,0,100,0,60010,4,0,0,62,0,0,0,0,0,0,7,0,0,0,-439.899,1538.91,19.636,3.14,"Teleport to Jewelcrafting"),
(@ENTRY,@SOURCETYPE,4,0,62,0,100,0,60010,5,0,0,62,0,0,0,0,0,0,7,0,0,0,-432.523,1521.33,19.547,4.138,"Teleport to Alchemy"),
(@ENTRY,@SOURCETYPE,5,0,62,0,100,0,60010,6,0,0,62,0,0,0,0,0,0,7,0,0,0,-345.285,1502.17,18.809,1.962,"Teleport to Blacksmithing"),
(@ENTRY,@SOURCETYPE,6,0,62,0,100,0,60010,7,0,0,62,0,0,0,0,0,0,7,0,0,0,-333.014,1525.34,17.986,1.627,"Teleport to Inscription");